//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Querys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Querys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseDatos.Querys", typeof(Querys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into BlackList (NroTelefono, idCarrier) values (&apos;{0}&apos;, 1).
        /// </summary>
        public static string BlackListIN {
            get {
                return ResourceManager.GetString("BlackListIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from BlackList where NroTelefono = &apos;{0}&apos; and idCarrier = 1.
        /// </summary>
        public static string BlackListOUT {
            get {
                return ResourceManager.GetString("BlackListOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from BlackList (nolock) where NroTelefono = &apos;{0}&apos; and idCarrier = 1.
        /// </summary>
        public static string Obtener_BlackList {
            get {
                return ResourceManager.GetString("Obtener_BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Suscripciones sus (nolock) 
        ///inner join SuscripcionesTipo tip (nolock) on tip.id = sus.idTipoSuscripcion 
        ///inner join SuscripcionesCarrierConfig scc (nolock) on scc.idSuscripcion = tip.id 
        ///inner join SMSPrecios pre (nolock) on pre.idPrecio = scc.idPrecio 
        ///where sus.NroTelefono = &apos;{0}&apos; and sus.idCarrier = 1 
        ///order by sus.FechaSuscripcion desc.
        /// </summary>
        public static string Obtener_Servicios {
            get {
                return ResourceManager.GetString("Obtener_Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Suscripciones sus (nolock) 
        ///inner join SuscripcionesTipo tip (nolock) on tip.id = sus.idTipoSuscripcion 
        ///where sus.NroTelefono = &apos;{0}&apos; and FechaBaja is NULL and sus.idCarrier = 1.
        /// </summary>
        public static string Obtener_Servicios_Activos {
            get {
                return ResourceManager.GetString("Obtener_Servicios_Activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Usuario (nolock) where [Usuario] = &apos;{0}&apos; and Contrasena = &apos;{1}&apos;.
        /// </summary>
        public static string Obtener_Usuario {
            get {
                return ResourceManager.GetString("Obtener_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Suscripciones set FechaBaja = getdate(), activa = 0, Status = 1, StatusText = &apos;Baja Carrier&apos; where NroTelefono = &apos;{0}&apos; and FechaBaja is NULL and idSuscripcion = {1}.
        /// </summary>
        public static string Update_Suscripcion {
            get {
                return ResourceManager.GetString("Update_Suscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Suscripciones set FechaBaja = getdate(), activa = 0, Status = 1, StatusText = &apos;Baja Carrier&apos; where NroTelefono = &apos;{0}&apos; and FechaBaja is NULL.
        /// </summary>
        public static string Update_Suscripcion_All {
            get {
                return ResourceManager.GetString("Update_Suscripcion_All", resourceCulture);
            }
        }
    }
}
